### ISSUE TITLE
Catalina compatible?

### ISSUE THREAD

**Issue by curdaneta** [davidlday/RemindersWidget#10]
Hello

Any chance to point how to use it with mac OS Catalina?
Thanks

**Comment by davidlday** [comment]
Hi! I haven't upgraded to Catalina yet but plan to do so in the next day or so. I'll dig into soon, but at this point, no, I don't know what changes are needed yet.

**Comment by curdaneta** [comment]
Great @davidlday take your time

**Comment by coolajami** [comment]
Same problem here, it seems that Reminders stopped supporting CALDAV in Catalina :/

**Comment by davidlday** [comment]
Starting to make some notes. 

1. Seems Catalina, and the new Reminders, has moved everything out of the old database (`~/Library/Calendars/Calendar Cache`) to a set of 3 (at least for me) new databases under `~/Library/Reminders/`. Will take some work to reverse engineer them.

**Comment by curdaneta** [comment]
Good to know that you're already working with Catalina @davidlday

**Comment by monkeemunk** [comment]
I started messing around with the code on my own in an attempt to get it working but got stuck and didn’t have time to keep playing with it — I’m happy to provide the modified .coffee if you’d like

**Comment by davidlday** [comment]
> I started messing around with the code on my own in an attempt to get it working but got stuck and didn’t have time to keep playing with it — I’m happy to provide the modified .coffee if you’d like

@monkeemunk - that would be a big help, thank you!

**Comment by davidlday** [comment]
Friends, I think I have it fixed. If any of you would be willing to test, I'd certainly appreciate it. Backup and replace `pending.sh` in the `reminders.widget` widget folder with the one from the [catalina branch](https://github.com/davidlday/RemindersWidget/blob/catalina/reminders.widget/pending.sh). I've also updated [reminders.widget.zip](https://github.com/davidlday/RemindersWidget/blob/catalina/reminders.widget.zip) if you want to download the whole package, but I've only changed the one file. Let me know results. Thanks for your patience!

**Comment by coolajami** [comment]
very good job! 
I just tried it in Catalina and it does work. I notice a glitch, it does not recognise the "listsToNotShow" parameter, and if you add a list there, the widget disappears again.

**Comment by curdaneta** [comment]
Great job @davidlday works like a charm!

**Comment by davidlday** [comment]
> very good job!
> I just tried it in Catalina and it does work. I notice a glitch, it does not recognise the "listsToNotShow" parameter, and if you add a list there, the widget disappears again.

@coolajami  - So I noticed while testing that if I updated the file(s) while Ubersicht was running, I'd get the behavior you described. The widget would disappear. If you haven't already, make sure you close Ubersicht, update the files again, then restart the application. Let me know the results, pls.

**Comment by coolajami** [comment]
Hi @davidlday 
I tried what you suggest and had the same problem again. 
However I found a solution:
tha name of each list in the listsToNotShow should go within apostrophes as below:

listsToNotShow:['ListToNotShow1','ListToNotShow2']


that solved it for me.
