### ISSUE TITLE
Not working on Big Sur

### ISSUE THREAD

**Issue by curdaneta** [davidlday/RemindersWidget#15]
Hello David

As expected, Reminders Widget it's not working on Big Sur.
I'm ready to help you make the fixes to make it work again.

Have a nice day

**Comment by curdaneta** [comment]
Hi David

Do you have an estimated date to start reviewing it?

**Comment by davidlday** [comment]
My apologies for taking so long. I have the fix available and will merge it in momentarily. I had a "magic number" still in the queries that broke on the update to Big Sur.

**Comment by davidlday** [comment]
Merged.

**Comment by curdaneta** [comment]
Thank you David. Worked like a charm!

**Comment by coolajami** [comment]
Thank you, works just fine!
