### ISSUE TITLE
Suport issue of macOS big sur

### ISSUE THREAD

**Issue by mamutou** [davidlday/RemindersWidget#18]
Is this plug have Suport issue of macOS big sur？
After updated from MacOS 10.5 to 11.2.1， this Reminderswidget don‘t work anymore. But other of the wigdget works well.
Do you have any idea to solve this?
Thanks.

**Comment by mamutou** [comment]
![image](https://user-images.githubusercontent.com/77874808/108533948-8335bb00-72d1-11eb-95c1-cb1bcc04a945.png)

**Comment by mamutou** [comment]
By the way, I love this ReminderWidget!! Thank you for your work.

**Comment by davidlday** [comment]
@mamutou  - apologies for not responding sooner. Yes, this runs on Big Sur, but you may need to upgrade to the latest version of this plugin. You might also run "Refresh All Widgets" to force a refresh. Let me know.

**Comment by mamutou** [comment]
I tried again by following the way you said，it seems do not work.  I also reinstalled the MacOS, only got the same result. And the wigdget or Ubersicht is newest version. Thank you anyway.

**Comment by davidlday** [comment]
@mamutou - sounds like this still isn't working for you, but also sounds like you've moved on. Is that the case? Can I close this issue, or do you still need help?
