### ISSUE TITLE
Black unformatted text at startup and random disappearing.

### ISSUE THREAD

**Issue by tiziano149** [davidlday/RemindersWidget#22]
Text appears black and unformatted, after the 'refreshFrequency' time has passed (6000ms), it jumps to the defined theme and correct formatting. After a while the widget vanishes to never comeback unless I refresh übersicht or restart. Following issues in the debug console:
![Bildschirmfoto 2021-04-25 um 13 18 10](https://user-images.githubusercontent.com/16635297/115991535-34eeb200-a5c9-11eb-91d9-246354d2f693.png)

**Comment by davidlday** [comment]
I suspect you don't have bash available. I have a few questions:

1) Is this a newer Mac?
2) What shell do you use by default (bash, zsh, etc)? 
3) Can you open a terminal, go to the `reminders.widget` directory, and run `./pending.sh`? Post the output here, pls.

**Comment by davidlday** [comment]
@tiziano149 - still having this problem, or can I close the issue?
