### ISSUE TITLE
No such table error

### ISSUE THREAD

**Issue by justeepin** [davidlday/RemindersWidget#24]
When I download and install the RemindersWidget I get the following error (I've not changed anything in the code):
`Error: no such table: Z_PRIMARYKEY
Error: near line 5: near "AND": syntax error
Error: near line 5: near "AND": syntax error
{ "tasks": [  ], "lists": [] }`

I'm on Mac OSX 10.15.7

**Comment by davidlday** [comment]
Hi - thanks for reporting your issue. Can you please run the following in a terminal and post the results:

```bash
cd "$HOME/Library/Application Support/Übersicht/widgets/reminders.widget"
./pending.sh
```

Let me know if you have any questions.

**Comment by justeepin** [comment]
Here's the output.
CC-X24RMD6R:~ kidddw$ cd "$HOME/Library/Application Support/Übersicht/widgets/reminders.widget"
CC-X24RMD6R:reminders.widget kidddw$ ./pending.sh
Error: no such table: Z_PRIMARYKEY
Error: near line 5: near "AND": syntax error
Error: near line 5: near "AND": syntax error
{ "tasks": [  ], "lists": [] }

**Comment by davidlday** [comment]
This has me a bit stumped. I hate to ask, but do you have items in you To Do lists?

Also, can you list out the following directory for me:

```bash
ls $HOME/Library/Reminders/Container_v1/Stores
```

**Comment by justeepin** [comment]
Yes, I have a todo in one of my lists in the Reminders app. 

Here's the output:
Data-37FA6822-CCA2-4605-9CA9-793260AD6574.sqlite
Data-37FA6822-CCA2-4605-9CA9-793260AD6574.sqlite-shm
Data-37FA6822-CCA2-4605-9CA9-793260AD6574.sqlite-wal
Data-8ECAA723-EFB5-429D-B009-7794970E99D2.sqlite
Data-8ECAA723-EFB5-429D-B009-7794970E99D2.sqlite-shm
Data-8ECAA723-EFB5-429D-B009-7794970E99D2.sqlite-wal
Data-C6387A24-D357-4576-ADF3-366E85DA60A8.sqlite
Data-C6387A24-D357-4576-ADF3-366E85DA60A8.sqlite-shm
Data-C6387A24-D357-4576-ADF3-366E85DA60A8.sqlite-wal
Data-E3486847-50C6-4014-ABB6-C393CAA2EE7C.sqlite
Data-E3486847-50C6-4014-ABB6-C393CAA2EE7C.sqlite-shm
Data-E3486847-50C6-4014-ABB6-C393CAA2EE7C.sqlite-wal
Data-local.sqlite
Data-local.sqlite-shm
Data-local.sqlite-wal

**Comment by justeepin** [comment]
I'm thinking it's something on my end. I tried two other widgets that access the Reminders app and they can't connect either. Sorry, I should have tried them before I posted an issue. I'm overdue for doing a clean install of the OS so maybe it'll work after that

**Comment by davidlday** [comment]
No worries. Let me know your outcome after a clean install. I'll leave this open for now.

**Comment by adamyalei** [comment]
@justeepin did u solve this issue at last? I'm having the same problem but didn't have a clue how to make it work. thanks for the help in advance.

**Comment by justeepin** [comment]
> @justeepin did u solve this issue at last? I'm having the same problem but didn't have a clue how to make it work. thanks for the help in advance.

No, I gave up.
