### ISSUE TITLE
Relocate position?

### ISSUE THREAD

**Issue by roadglide03** [davidlday/RemindersWidget#8]
Love the app but I need to reposition it.  Tried the normal way but dent work since there is a default style.  Is there a way to add something like: 

    top: 1%
    left: 70%

Thanks Andy

**Comment by davidlday** [comment]
Hey! Apologies for not getting back to you sooner. I should have an answer for you shortly. The widget's designed to allow you to make your own custom theme that would let you do this, but I haven't written instructions for how to do so yet.

**Comment by davidlday** [comment]
Okay - Let me know if this works. I'm assuming you've set up the widget in `~/Library/Application Support/Übersicht/widgets/reminders.widget` and just refer to it as `reminders.widget`.

1. Open `reminders.widget/reminders.coffee` in your favorite text editor.
1. Change line 7 from `theme: 'default'` to `theme: 'custom'`, save, and close.
1. Copy `reminders.widget/styles/default.css` (or `reminders.widget/styles/sidebar.css`) to `reminders.widget/styles/custom.css`.
1. Open `reminders.widget/styles/custom.css` and make any changes you like, save, and close.

On the next refresh of Übersicht, your changes should show up.

- D

**Comment by roadglide03** [comment]
Crap I missed that completely, sorry about that its so obvious, thanks got it the way I like, Andy

**Comment by davidlday** [comment]
@roadglide03 - no worries! Let me know if you run into any other problems.
